version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo-local
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
